# Sascha Nesterovic

PRODUCT_COPY_FILES += \
    vendor/samsung/great-common/proprietary/app/FFFFFFFF000000000000000000000001.drbin:system/app/FFFFFFFF000000000000000000000001.drbin \
    vendor/samsung/great-common/proprietary/app/mcRegistry/00060308060501020000000000000000.tlbin:system/app/mcRegistry/00060308060501020000000000000000.tlbin \
    vendor/samsung/great-common/proprietary/app/mcRegistry/0706000000000000000000000000004d.tlbin:system/app/mcRegistry/0706000000000000000000000000004d.tlbin \
    vendor/samsung/great-common/proprietary/app/mcRegistry/07010000000000000000000000000000.tlbin:system/app/mcRegistry/07010000000000000000000000000000.tlbin \
    vendor/samsung/great-common/proprietary/app/mcRegistry/08130000000000000000000000000000.tlbin:system/app/mcRegistry/08130000000000000000000000000000.tlbin \
    vendor/samsung/great-common/proprietary/app/mcRegistry/ffffffff00000000000000000000000a.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000a.tlbin \
    vendor/samsung/great-common/proprietary/app/mcRegistry/ffffffff00000000000000000000000c.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000c.tlbin \
    vendor/samsung/great-common/proprietary/app/mcRegistry/ffffffff00000000000000000000000d.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000d.tlbin \
    vendor/samsung/great-common/proprietary/app/mcRegistry/ffffffff00000000000000000000000e.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000e.tlbin \
    vendor/samsung/great-common/proprietary/app/mcRegistry/ffffffff00000000000000000000000f.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000f.tlbin \
    vendor/samsung/great-common/proprietary/app/mcRegistry/ffffffff00000000000000000000003e.tlbin:system/app/mcRegistry/ffffffff00000000000000000000003e.tlbin \
    vendor/samsung/great-common/proprietary/app/mcRegistry/ffffffff000000000000000000000004.tlbin:system/app/mcRegistry/ffffffff000000000000000000000004.tlbin \
    vendor/samsung/great-common/proprietary/app/mcRegistry/ffffffff000000000000000000000005.tlbin:system/app/mcRegistry/ffffffff000000000000000000000005.tlbin \
    vendor/samsung/great-common/proprietary/app/mcRegistry/ffffffff000000000000000000000012.tlbin:system/app/mcRegistry/ffffffff000000000000000000000012.tlbin \
    vendor/samsung/great-common/proprietary/app/mcRegistry/ffffffff000000000000000000000013.tlbin:system/app/mcRegistry/ffffffff000000000000000000000013.tlbin \
    vendor/samsung/great-common/proprietary/app/mcRegistry/ffffffff000000000000000000000016.tlbin:system/app/mcRegistry/ffffffff000000000000000000000016.tlbin \
    vendor/samsung/great-common/proprietary/app/mcRegistry/ffffffff000000000000000000000017.tlbin:system/app/mcRegistry/ffffffff000000000000000000000017.tlbin \
    vendor/samsung/great-common/proprietary/app/mcRegistry/ffffffff000000000000000000000030.tlbin:system/app/mcRegistry/ffffffff000000000000000000000030.tlbin \
    vendor/samsung/great-common/proprietary/app/mcRegistry/ffffffff000000000000000000000038.tlbin:system/app/mcRegistry/ffffffff000000000000000000000038.tlbin \
    vendor/samsung/great-common/proprietary/app/mcRegistry/ffffffff000000000000000000000041.tlbin:system/app/mcRegistry/ffffffff000000000000000000000041.tlbin \
    vendor/samsung/great-common/proprietary/app/mcRegistry/ffffffff000000000000000000000045.tlbin:system/app/mcRegistry/ffffffff000000000000000000000045.tlbin \
    vendor/samsung/great-common/proprietary/app/mcRegistry/ffffffff000000000000000000000047.tlbin:system/app/mcRegistry/ffffffff000000000000000000000047.tlbin \
    vendor/samsung/great-common/proprietary/app/mcRegistry/ffffffff000000000000000000000059.tlbin:system/app/mcRegistry/ffffffff000000000000000000000059.tlbin \
    vendor/samsung/great-common/proprietary/app/mcRegistry/ffffffff000000000000000000000060.tlbin:system/app/mcRegistry/ffffffff000000000000000000000060.tlbin \
    vendor/samsung/great-common/proprietary/app/mcRegistry/ffffffffd0000000000000000000000a.tlbin:system/app/mcRegistry/ffffffffd0000000000000000000000a.tlbin \
    vendor/samsung/great-common/proprietary/app/mcRegistry/ffffffffd0000000000000000000000e.tlbin:system/app/mcRegistry/ffffffffd0000000000000000000000e.tlbin \
    vendor/samsung/great-common/proprietary/app/mcRegistry/ffffffffd0000000000000000000001a.tlbin:system/app/mcRegistry/ffffffffd0000000000000000000001a.tlbin \
    vendor/samsung/great-common/proprietary/app/mcRegistry/ffffffffd00000000000000000000004.tlbin:system/app/mcRegistry/ffffffffd00000000000000000000004.tlbin \
    vendor/samsung/great-common/proprietary/app/mcRegistry/ffffffffd00000000000000000000014.tlbin:system/app/mcRegistry/ffffffffd00000000000000000000014.tlbin \
    vendor/samsung/great-common/proprietary/app/mcRegistry/ffffffffd00000000000000000000016.tlbin:system/app/mcRegistry/ffffffffd00000000000000000000016.tlbin \
    vendor/samsung/great-common/proprietary/app/mcRegistry/ffffffffd00000000000000000000017.tlbin:system/app/mcRegistry/ffffffffd00000000000000000000017.tlbin \
    vendor/samsung/great-common/proprietary/app/mcRegistry/fffffffff0000000000000000000001b.tlbin:system/app/mcRegistry/fffffffff0000000000000000000001b.tlbin \
    vendor/samsung/great-common/proprietary/app/mcRegistry/fffffffff0000000000000000000001e.tlbin:system/app/mcRegistry/fffffffff0000000000000000000001e.tlbin \
    vendor/samsung/great-common/proprietary/bin/bcm_sensorhub_a1.patch:system/bin/bcm_sensorhub_a1.patch \
    vendor/samsung/great-common/proprietary/bin/cbd:system/bin/cbd \
    vendor/samsung/great-common/proprietary/bin/gps.cer:system/bin/gps.cer \
    vendor/samsung/great-common/proprietary/bin/gpsd:system/bin/gpsd \
    vendor/samsung/great-common/proprietary/etc/init/servicemanager.rc:system/etc/init/servicemanager.rc \
    vendor/samsung/great-common/proprietary/etc/init/surfaceflinger.rc:system/etc/init/surfaceflinger.rc \
    vendor/samsung/great-common/proprietary/etc/init/uncrypt.rc:system/etc/init/uncrypt.rc \
    vendor/samsung/great-common/proprietary/etc/init/vdc.rc:system/etc/init/vdc.rc \
    vendor/samsung/great-common/proprietary/etc/init/visiondserver.rc:system/etc/init/visiondserver.rc \
    vendor/samsung/great-common/proprietary/etc/init/servicemanager.rc:system/etc/init/servicemanager.rc \
    vendor/samsung/great-common/proprietary/etc/init/surfaceflinger.rc:system/etc/init/surfaceflinger.rc \
    vendor/samsung/great-common/proprietary/etc/init/uncrypt.rc:system/etc/init/uncrypt.rc \
    vendor/samsung/great-common/proprietary/etc/init/vdc.rc:system/etc/init/vdc.rc \
    vendor/samsung/great-common/proprietary/etc/init/visiondserver.rc:system/etc/init/visiondserver.rc \
    vendor/samsung/great-common/proprietary/bin/lhd:system/bin/lhd \
    vendor/samsung/great-common/proprietary/bin/mcDriverDaemon:system/bin/mcDriverDaemon \
    vendor/samsung/great-common/proprietary/bin/rild:system/bin/rild \
    vendor/samsung/great-common/proprietary/bin/sensorhubservice:system/bin/sensorhubservice \
    vendor/samsung/great-common/proprietary/bin/tlc_server:system/bin/tlc_server \
    vendor/samsung/great-common/proprietary/etc/security_nfc_profile.dat:system/etc/security_nfc_profile.at \
    vendor/samsung/great-common/proprietary/etc/firmware/cs47l92-dsp1-dsd-176.4kHz.wmfw:system/etc/firmware/cs47l92-dsp1-dsd-176.4kHz.wmfw \
    vendor/samsung/great-common/proprietary/etc/firmware/cs47l92-dsp1-trace.wmfw:system/etc/firmware/cs47l92-dsp1-trace.wmfw \
    vendor/samsung/great-common/proprietary/etc/firmware/cs47l92-dsp1-dsd-352.8kHz.wmfw:system/etc/firmware/cs47l92-dsp1-dsd-352.8kHz.wmfw \
    vendor/samsung/great-common/proprietary/etc/init/atrace.rc:system/etc/init/atrace.rc \
    vendor/samsung/great-common/proprietary/etc/init/audioserver.rc:system/etc/init/audioserver.rc \
    vendor/samsung/great-common/proprietary/etc/init/bootanim.rc:system/etc/init/bootanim.rc \
    vendor/samsung/great-common/proprietary/etc/init/bootstat.rc:system/etc/init/bootstat.rc \
    vendor/samsung/great-common/proprietary/etc/init/cameraserver.rc:system/etc/init/cameraserver.rc \
    vendor/samsung/great-common/proprietary/etc/init/debuggerd64.rc:system/etc/init/debuggerd64.rc \
    vendor/samsung/great-common/proprietary/etc/init/debuggerd.rc:system/etc/init/debuggerd.rc \
    vendor/samsung/great-common/proprietary/etc/init/drmserver.rc:system/etc/init/drmserver.rc \
    vendor/samsung/great-common/proprietary/etc/init/dumpstate.rc:system/etc/init/dumpstate.rc \
    vendor/samsung/great-common/proprietary/etc/init/gatekeeperd.rc:system/etc/init/gatekeeperd.rc \
    vendor/samsung/great-common/proprietary/etc/init/init.rilcommon.rc:system/etc/init/init.rilcommon.rc \
    vendor/samsung/great-common/proprietary/etc/init/installd.rc:system/etc/init/installd.rc \
    vendor/samsung/great-common/proprietary/etc/init/keystore.rc:system/etc/init/keystore.rc \
    vendor/samsung/great-common/proprietary/etc/init/lmkd.rc:system/etc/init/lmkd.rc \
    vendor/samsung/great-common/proprietary/etc/init/logd.rc:system/etc/init/logd.rc \
    vendor/samsung/great-common/proprietary/etc/init/mdnsd.rc:system/etc/init/mdnsd.rc \
    vendor/samsung/great-common/proprietary/etc/init/mediacodec.rc:system/etc/init/mediacodec.rc \
    vendor/samsung/great-common/proprietary/etc/init/mediaextractor.rc:system/etc/init/mediaextractor.rc \
    vendor/samsung/great-common/proprietary/etc/init/mediadrmserver.rc:system/etc/init/mediadrmserver.rc \
    vendor/samsung/great-common/proprietary/etc/init/mediaserver.rc:system/etc/init/mediaserver.rc \
    vendor/samsung/great-common/proprietary/etc/init/mtpd.rc:system/etc/init/mtpd.rc \
    vendor/samsung/great-common/proprietary/etc/init/netd.rc:system/etc/init/netd.rc \
    vendor/samsung/great-common/proprietary/etc/init/powersnd.rc:system/etc/init/powersd.rc \
    vendor/samsung/great-common/proprietary/etc/init/racoon.rc:system/etc/init/racoon.rc \
    vendor/samsung/great-common/proprietary/etc/init/servicemanager.rc:system/etc/init/servicemanager.rc \
    vendor/samsung/great-common/proprietary/etc/init/surfaceflinger.rc:system/etc/init/surfaceflinger.rc \
    vendor/samsung/great-common/proprietary/etc/init/uncrypt.rc:system/en.rc \
    vendor/samsung/great-common/proprietary/etc/init/servicemanager.rc:system/etc/init/servicemanager.rc \
    vendor/samsung/great-common/proprietary/etc/init/surfaceflinger.rc:system/etc/init/surfaceflinger.rc \
    vendor/samsung/great-common/proprietary/etc/init/vdc.rc:system/etc/init/vdc.rc \
    vendor/samsung/great-common/proprietary/etc/init/visiondserver.rc:system/etc/init/visiondserver.rc \
    vendor/samsung/great-common/proprietary/init/uncrypt.rc:system/etc/init/uncrypt.rc  \
    vendor/samsung/great-common/proprietary/etc/init/vdc.rc:system/etc/init/vdc.rc \
    vendor/samsung/great-common/proprietary/etc/init/visiondserver.rc:system/etc/init/visiondserver.rc \
    vendor/samsung/great-common/proprietary/etc/init/vold.rc:system/etc/init/vold.rc \
    vendor/samsung/great-common/proprietary/etc/nfc/sec_s3nrn82_rfreg.bin:system/etc/nfc/sec_s3nrn82_rfreg.bin \
    vendor/samsung/great-common/proprietary/etc/nfc/SGP/sec_s3nrn82_rfreg.bin:system/etc/nfc/SGP/sec_s3nrn82_rfreg.bin \
    vendor/samsung/great-common/proprietary/etc/sensors/hals.conf:system/etc/sensors/hals.conf \
    vendor/samsung/great-common/proprietary/etc/wifi/bcmdhd_clm.blob:system/etc/wifi/bcmdhd_clm.blob \
    vendor/samsung/great-common/proprietary/etc/wifi/bcmdhd_mfg.bin:system/etc/wifi/bcmdhd_mfg.bin \
    vendor/samsung/great-common/proprietary/etc/wifi/bcmdhd_mfg.bin_a0:system/etc/wifi/bcmdhd_mfg.bin_a0 \
    vendor/samsung/great-common/proprietary/etc/wifi/bcmdhd_mfg.bin_a0_ePA:system/etc/wifi/bcmdhd_mfg.bin_a0_ePA \
    vendor/samsung/great-common/proprietary/etc/wifi/bcmdhd_mfg.bin_a1:system/etc/wifi/bcmdhd_mfg.bin_a1 \
    vendor/samsung/great-common/proprietary/etc/wifi/bcmdhd_sta.bin:system/etc/wifi/bcmdhd_sta.bin \
    vendor/samsung/great-common/proprietary/etc/wifi/bcmdhd_sta.bin_a0_ePA:system/etc/wifi/bcmdhd_sta.bin_a0_ePA \
    vendor/samsung/great-common/proprietary/etc/wifi/bcmdhd_sta.bin_a1:system/etc/wifi/bcmdhd_sta.bin_a1 \
    vendor/samsung/great-common/proprietary/etc/wifi/nvram_mfg.txt:system/etc/wifi/nvram_mfg.txt \
    vendor/samsung/great-common/proprietary/etc/wifi/nvram_mfg.txt_a0:system/etc/wifi/nvram_mfg.txt_a0 \
    vendor/samsung/great-common/proprietary/etc/wifi/nvram_mfg.txt_a0_ePA:system/etc/wifi/nvram_mfg.txt_a0_ePA \
    vendor/samsung/great-common/proprietary/etc/wifi/nvram_mfg.txt_murata_r012_a1:system/etc/wifi/nvram_mfg.txt_murata_r012_a1 \
    vendor/samsung/great-common/proprietary/etc/wifi/nvram_mfg.txt_murata_r013_b0:system/etc/wifi/nvram_mfg.txt_murata_r013_b0 \
    vendor/samsung/great-common/proprietary/etc/wifi/nvram_mfg.txt_murata_r014_b0:system/etc/wifi/nvram_mfg.txt_murata_r014_b0 \
    vendor/samsung/great-common/proprietary/etc/wifi/nvram_mfg.txt_murata_r020_b0:system/etc/wifi/nvram_mfg.txt_murata_r020_b0 \
    vendor/samsung/great-common/proprietary/etc/wifi/nvram_mfg.txt_r01a_a1:system/etc/wifi/nvram_mfg.txt_r01a_a1 \
    vendor/samsung/great-common/proprietary/etc/wifi/nvram_mfg.txt_r01d_b0:system/etc/wifi/nvram_mfg.txt_r01d_b0 \
    vendor/samsung/great-common/proprietary/etc/wifi/nvram_mfg.txt_r01f_b0:system/etc/wifi/nvram_mfg.txt_r01f_b0 \
    vendor/samsung/great-common/proprietary/etc/wifi/nvram_mfg.txt_r01i_b0:system/etc/wifi/nvram_mfg.txt_r01i_b0 \
    vendor/samsung/great-common/proprietary/etc/wifi/nvram_mfg.txt_r02a_a1:system/etc/wifi/nvram_mfg.txt_r02a_a1 \
    vendor/samsung/great-common/proprietary/etc/wifi/nvram_mfg.txt_r02c_a1:system/etc/wifi/nvram_mfg.txt_r02c_a1 \
    vendor/samsung/great-common/proprietary/etc/wifi/nvram_mfg.txt_r02g_b0:system/etc/wifi/nvram_mfg.txt_r02g_b0 \
    vendor/samsung/great-common/proprietary/etc/wifi/nvram_mfg.txt_r02j_b0:system/etc/wifi/nvram_mfg.txt_r02j_b0 \
    vendor/samsung/great-common/proprietary/etc/wifi/nvram_net.txt:system/etc/wifi/nvram_net.txt \
    vendor/samsung/great-common/proprietary/etc/wifi/nvram_net.txt_a0:system/etc/wifi/nvram_net.txt_a0 \
    vendor/samsung/great-common/proprietary/etc/wifi/nvram_net.txt_a0_ePA:system/etc/wifi/nvram_net.txt_a0_ePA \
    vendor/samsung/great-common/proprietary/etc/wifi/nvram_net.txt_murata_r012_a1:system/etc/wifi/nvram_net.txt_murata_r012_a1 \
    vendor/samsung/great-common/proprietary/etc/wifi/nvram_net.txt_murata_r013_b0:system/etc/wifi/nvram_net.txt_murata_r013_b0 \
    vendor/samsung/great-common/proprietary/etc/wifi/nvram_net.txt_murata_r014_b0:system/etc/wifi/nvram_net.txt_murata_r014_b0 \
    vendor/samsung/great-common/proprietary/etc/wifi/nvram_net.txt_murata_r020_b0:system/etc/wifi/nvram_net.txt_murata_r020_b0 \
    vendor/samsung/great-common/proprietary/etc/wifi/nvram_net.txt_r01a_a1:system/etc/wifi/nvram_net.txt_r01a_a1 \
    vendor/samsung/great-common/proprietary/etc/wifi/nvram_net.txt_r01d_b0:system/etc/wifi/nvram_net.txt_r01d_b0 \
    vendor/samsung/great-common/proprietary/etc/wifi/nvram_net.txt_r01f_b0:system/etc/wifi/nvram_net.txt_r01f_b0 \
    vendor/samsung/great-common/proprietary/etc/wifi/nvram_net.txt_r01i_b0:system/etc/wifi/nvram_net.txt_r01i_b0 \
    vendor/samsung/great-common/proprietary/etc/wifi/nvram_net.txt_r02a_a1:system/etc/wifi/nvram_net.txt_r02a_a1 \
    vendor/samsung/great-common/proprietary/etc/wifi/nvram_net.txt_r02g_b0:system/etc/wifi/nvram_net.txt_r02g_b0 \
    vendor/samsung/great-common/proprietary/etc/wifi/nvram_net.txt_r02j_b0:system/etc/wifi/nvram_net.txt_r02j_b0 \
    vendor/samsung/great-common/proprietary/etc/wifi/nvram.txt_murata_r031_b0:system/etc/wifi/nvram.txt_murata_r031_b0 \
    vendor/samsung/great-common/proprietary/etc/wifi/nvram.txt_murata_r032_b0:system/etc/wifi/nvram.txt_murata_r032_b0 \
    vendor/samsung/great-common/proprietary/etc/wifi/nvram.txt_murata_r033_b0:system/etc/wifi/nvram.txt_murata_r033_b0 \
    vendor/samsung/great-common/proprietary/etc/wifi/nvram.txt_r02j_b0:system/etc/wifi/nvram.txt_r02j_b0 \
    vendor/samsung/great-common/proprietary/etc/wifi/nvram.txt_r02j_b0:system/etc/wifi/nvram.txt_r02j_b0 \
    vendor/samsung/great-common/proprietary/etc/wifi/p2p_supplicant_overlay.conf:system/etc/wifi/p2p_supplicant_overlay.conf \
    vendor/samsung/great-common/proprietary/etc/wifi/wldu.conf:system/etc/wifi/wldu.conf \
    vendor/samsung/great-common/proprietary/etc/wifi/wpa_supplicant.conf:system/etc/wifi/wpa_supplicant.conf \
    vendor/samsung/great-common/proprietary/etc/wifi/wpa_supplicant_overlay.conf:system/etc/wifi/wpa_supplicant_overlay.conf \
    vendor/samsung/great-common/proprietary/lib/libacryl.so:system/lib/libacryl.so \
    vendor/samsung/great-common/proprietary/lib/libapa_control.so:system/lib/libapa_control.so \
    vendor/samsung/great-common/proprietary/lib/libapa.so:system/lib/libapa.so \
    vendor/samsung/great-common/proprietary/lib/libaudiopolicyenginedefault.so:system/lib/libaudiopolicyenginedefault.so \
    vendor/samsung/great-common/proprietary/lib/libaudio-ril.so:system/lib/libaudio-ril.so \
    vendor/samsung/great-common/proprietary/lib/libaudioroute.so:system/lib/libaudioroute.so \
    vendor/samsung/great-common/proprietary/lib/libaudiosa.so:system/lib/libaudiosa.so \
    vendor/samsung/great-common/proprietary/lib/libaudioutils.so:system/lib/libaudioutils.so \
    vendor/samsung/great-common/proprietary/lib/libbauthtzcommon.so:system/lib/libbauthtzcommon.so \
    vendor/samsung/great-common/proprietary/lib/libcamera_client.so:system/lib/libcamera_client.so \
    vendor/samsung/great-common/proprietary/lib/libcamera_metadata.so:system/lib/libcamera_metadata.so \
    vendor/samsung/great-common/proprietary/lib/libedmnativehelper.so:system/lib/libedmnativehelper.so \
    vendor/samsung/great-common/proprietary/lib/libexynoscamera3.so:system/lib/libexynoscamera3.so \
    vendor/samsung/great-common/proprietary/lib/libexynoscamera.so:system/lib/libexynoscamera.so \
    vendor/samsung/great-common/proprietary/lib/libexynosgscaler.so:system/lib/libexynosgscaler.so \
    vendor/samsung/great-common/proprietary/lib/libExynosOMX_Core.so:system/lib/libExynosOMX_Core.so \
    vendor/samsung/great-common/proprietary/lib/libExynosOMX_Resourcemanager.so:system/lib/libExynosOMX_Resourcemanager.so \
    vendor/samsung/great-common/proprietary/lib/libexynosscaler.so:system/lib/libexynosscaler.so \
    vendor/samsung/great-common/proprietary/lib/libexynosutils.so:system/lib/libexynosutils.so \
    vendor/samsung/great-common/proprietary/lib/libexynosv4l2.so:system/lib/libexynosv4l2.so \
    vendor/samsung/great-common/proprietary/lib/libfloatingfeature.so:system/lib/libfloatingfeature.so \
    vendor/samsung/great-common/proprietary/lib/libhiddensound.so:system/lib/libhiddensound.so \
    vendor/samsung/great-common/proprietary/lib/libHMT.so:system/proprietary/lib/libHMT.so \
    vendor/samsung/great-common/proprietary/lib/libion.so:system/lib/libion.so \
    vendor/samsung/great-common/proprietary/lib/libjackshm.so:system/lib/libjackshm.so \
    vendor/samsung/great-common/proprietary/lib/libjansson.so:system/lib/libjansson.so \
    vendor/samsung/great-common/proprietary/lib/libmediautils.so:system/lib/libmediautils.so \
    vendor/samsung/great-common/proprietary/lib/libmysound.so:system/lib/libmysound.so \
    vendor/samsung/great-common/proprietary/lib/liboemcrypto.so:system/lib/liboemcrypto.so \
    vendor/samsung/great-common/proprietary/lib/libprotobuf-cpp-full.so:system/lib/libprotobuf-cpp-full.so \
    vendor/samsung/great-common/proprietary/lib/librecordalive.so:system/lib/librecordalive.so \
    vendor/samsung/great-common/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
    vendor/samsung/great-common/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/samsung/great-common/proprietary/lib/librilutils.so:system/lib/librilutils.so \
    vendor/samsung/great-common/proprietary/lib/lib_SA_GoogleFX_ver124b.so:system/lib/lib_SA_GoogleFX_ver124b.so \
    vendor/samsung/great-common/proprietary/lib/libsamsungDiamondVoiceExtV4.so:system/lib/libsamsungDiamondVoiceExtV4.so \
    vendor/samsung/great-common/proprietary/lib/libSamsungPostProcessConvertor.so:system/lib/libSamsungPostProcessConvertor.so \
    vendor/samsung/great-common/proprietary/lib/lib_SamsungRec_06003.so:system/lib/lib_SamsungRec_06003.so \
    vendor/samsung/great-common/proprietary/lib/libsamsungSoundbooster_plus.so:system/lib/libsamsungSoundbooster_plus.so \
    vendor/samsung/great-common/proprietary/lib/libsecaudioinfo.so:system/lib/libsecaudioinfo.so \
    vendor/samsung/great-common/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
    vendor/samsung/great-common/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
    vendor/samsung/great-common/proprietary/lib/libsec-ril-dsds.so:system/lib/libsec-ril-dsds.so \
    vendor/samsung/great-common/proprietary/lib/libsec-ril.so:system/lib/libsec-ril.so \
    vendor/samsung/great-common/proprietary/lib/libsensorhub.so:system/lib/libsensorhub.so \
    vendor/samsung/great-common/proprietary/lib/libsensorlistener.so:system/lib/libsensorlistener.so \
    vendor/samsung/great-common/proprietary/lib/lib_soundaliveresampler.so:system/lib/lib_soundaliveresampler.so \
    vendor/samsung/great-common/proprietary/lib/lib_SoundAlive_SRC384_ver300.so:system/lib/lib_SoundAlive_SRC384_ver300.so \
    vendor/samsung/great-common/proprietary/lib/lib_SoundBooster_ver800.so:system/lib/lib_SoundBooster_ver800.so \
    vendor/samsung/great-common/proprietary/lib/libspeexresampler.so:system/lib/libspeexresampler.so \
    vendor/samsung/great-common/proprietary/lib/libsynaFpSensorTestNwd.so:system/lib/libsynaFpSensorTestNwd.so \
    vendor/samsung/great-common/proprietary/lib/libtinyalsa.so:system/lib/libtinyalsa.so \
    vendor/samsung/great-common/proprietary/lib/libtinycompress.so:system/lib/libtinycompress.so \
    vendor/samsung/great-common/proprietary/lib/libtlc_direct_comm.so:system/lib/libtlc_direct_comm.so \
    vendor/samsung/great-common/proprietary/lib/libtlcotp.so:system/lib/libtlcotp.so \
    vendor/samsung/great-common/proprietary/lib/libtlc_proxy_comm.so:system/lib/libtlc_proxy_comm.so \
    vendor/samsung/great-common/proprietary/lib/libtlc_spay.so:system/lib/libtlc_spay.so \
    vendor/samsung/great-common/proprietary/lib/libtlc_tima_atn.so:system/lib/libtlc_tima_atn.so \
    vendor/samsung/great-common/proprietary/lib/libtlc_tima_pkm.so:system/lib/libtlc_tima_pkm.so \
    vendor/samsung/great-common/proprietary/lib/libtlc_tz_dcm.so:system/lib/libtlc_tz_dcm.so \
    vendor/samsung/great-common/proprietary/lib/libtlc_tz_esecomm.so:system/lib/libtlc_tz_esecomm.so \
    vendor/samsung/great-common/proprietary/lib/libtlc_tz_iccc.so:system/lib/libtlc_tz_iccc.so \
    vendor/samsung/great-common/proprietary/lib/libtlc_tz_keystore.so:system/lib/libtlc_tz_keystore.so \
    vendor/samsung/great-common/proprietary/lib/libtzyfingr.so:system/lib/libtzyfingr.so \
    vendor/samsung/great-common/proprietary/lib/libuniapi.so:system/lib/libuniapi.so \
    vendor/samsung/great-common/proprietary/lib/libuniplugin.so:system/lib/libuniplugin.so \
    vendor/samsung/great-common/proprietary/lib/libwrappergps.so:system/lib/libwrappergps.so \
    vendor/samsung/great-common/proprietary/lib/libxml2.so:system/lib/libxml2.so \
    vendor/samsung/great-common/proprietary/lib/sensors.bio.so:system/lib/sensors.bio.so \
    vendor/samsung/great-common/proprietary/lib/sensors.sensorhub.so:system/lib/sensors.sensorhub.so \
    vendor/samsung/great-common/proprietary/lib/hw/audio.playback_record.default.so:system/lib/hw/audio.playback_record.default.so \
    vendor/samsung/great-common/proprietary/lib/hw/audio_policy.default.so:system/lib/hw/audio_policy.default.so \
    vendor/samsung/great-common/proprietary/lib/hw/audio.primary.default.so:system/lib/hw/audio.primary.default.so \
    vendor/samsung/great-common/proprietary/lib/hw/audio.primary.goldfish.so:system/lib/hw/audio.primary.goldfish.so \
    vendor/samsung/great-common/proprietary/lib/hw/audio.primary.universal8895.so:system/lib/hw/audio.primary.universal8895.so \
    vendor/samsung/great-common/proprietary/lib/hw/audio.r_submix.default.so:system/lib/hw/audio.r_submix.default.so \
    vendor/samsung/great-common/proprietary/lib/hw/audio.tms.default.so:system/lib/hw/audio.tms.default.so \
    vendor/samsung/great-common/proprietary/lib/hw/audio.usb.default.so:system/lib/hw/audio.usb.default.so \
    vendor/samsung/great-common/proprietary/lib/hw/bluetooth.default.so:system/lib/hw/bluetooth.default.so \
    vendor/samsung/great-common/proprietary/lib/hw/camera.goldfish.jpeg.so:system/lib/hw/camera.goldfish.jpeg.so \
    vendor/samsung/great-common/proprietary/lib/hw/camera.goldfish.so:system/lib/hw/camera.goldfish.so \
    vendor/samsung/great-common/proprietary/lib/hw/camera.universal8895.so:system/lib/hw/camera.universal8895.so \
    vendor/samsung/great-common/proprietary/lib/hw/fingerprint.default.so:system/lib/hw/fingerprint.default.so \
    vendor/samsung/great-common/proprietary/lib/hw/fingerprint.goldfish.so:system/lib/hw/fingerprint.goldfish.so \
    vendor/samsung/great-common/proprietary/lib/hw/fingerprint.ranchu.so:system/lib/hw/fingerprint.ranchu.so \
    vendor/samsung/great-common/proprietary/lib/hw/gatekeeper.exynos8895.so:system/lib/hw/gatekeeper.exynos8895.so \
    vendor/samsung/great-common/proprietary/lib/hw/gps.goldfish.so:system/lib/hw/gps.goldfish.so \
    vendor/samsung/great-common/proprietary/lib/hw/gps.ranchu.so:system/lib/hw/gps.ranchu.so \
    vendor/samsung/great-common/proprietary/lib/hw/gralloc.default.so:system/lib/hw/gralloc.default.so \
    vendor/samsung/great-common/proprietary/lib/hw/gralloc.exynos5.so:system/lib/hw/gralloc.exynos5.so \
    vendor/samsung/great-common/proprietary/lib/hw/hwcomposer.exynos5.so:system/lib/hw/hwcomposer.exynos5.so \
    vendor/samsung/great-common/proprietary/lib/hw/keystore.exynos8895.so:system/lib/hw/keystore.exynos8895.so \
    vendor/samsung/great-common/proprietary/lib/hw/lights.goldfish.so:system/lib/hw/lights.goldfish.so \
    vendor/samsung/great-common/proprietary/lib/hw/local_time.default.so:system/lib/hw/local_time.default.so \
    vendor/samsung/great-common/proprietary/lib/hw/memtrack.exynos5.so:system/lib/hw/memtrack.exynos5.so \
    vendor/samsung/great-common/proprietary/lib/hw/nfc_nci.universal8895.so:system/lib/hw/nfc_nci.universal8895.so \
    vendor/samsung/great-common/proprietary/lib/hw/power.default.so:system/lib/hw/power.default.so \
    vendor/samsung/great-common/proprietary/lib/hw/sensorhubs.universal8895.so:system/lib/hw/sensorhubs.universal8895.so \
    vendor/samsung/great-common/proprietary/lib/hw/sensors.goldfish.so:system/lib/hw/sensors.goldfish.so \
    vendor/samsung/great-common/proprietary/lib/hw/sensors.ranchu.so:system/lib/hw/sensors.ranchu.so \
    vendor/samsung/great-common/proprietary/lib/hw/sensors.universal8895.so:system/lib/hw/sensors.universal8895.so \
    vendor/samsung/great-common/proprietary/lib/hw/thermal.exynos5.so:system/lib/hw/thermal.exynos5.so \
    vendor/samsung/great-common/proprietary/lib/hw/vibrator.default.so:system/lib/hw/vibrator.default.so \
    vendor/samsung/great-common/proprietary/lib/hw/vibrator.goldfish.so:system/lib/hw/vibrator.goldfish.so \
    vendor/samsung/great-common/proprietary/lib/hw/vr.default.so:system/lib/hw/vr.default.so \
    vendor/samsung/great-common/proprietary/lib/omx/libOMX.Exynos.AVC.Decoder.so:system/lib/omx/libOMX.Exynos.AVC.Decoder.so \
    vendor/samsung/great-common/proprietary/lib/omx/libOMX.Exynos.AVC.Encoder.so:system/lib/omx/libOMX.Exynos.AVC.Encoder.so \
    vendor/samsung/great-common/proprietary/lib/omx/libOMX.Exynos.HEVC.Decoder.so:system/lib/omx/libOMX.Exynos.HEVC.Decoder.so \
    vendor/samsung/great-common/proprietary/lib/omx/libOMX.Exynos.HEVC.Encoder.so:system/lib/omx/libOMX.Exynos.HEVC.Encoder.so \
    vendor/samsung/great-common/proprietary/lib/omx/libOMX.Exynos.MPEG4.Decoder.so:system/lib/omx/libOMX.Exynos.MPEG4.Decoder.so \
    vendor/samsung/great-common/proprietary/lib/omx/libOMX.Exynos.MPEG4.Encoder.so:system/lib/omx/libOMX.Exynos.MPEG4.Encoder.so \
    vendor/samsung/great-common/proprietary/lib/omx/libOMX.Exynos.VP8.Decoder.so:system/lib/omx/libOMX.Exynos.VP8.Decoder.so \
    vendor/samsung/great-common/proprietary/lib/omx/libOMX.Exynos.VP8.Encoder.so:system/lib/omx/libOMX.Exynos.VP8.Encoder.so \
    vendor/samsung/great-common/proprietary/lib/omx/libOMX.Exynos.VP9.Decoder.so:system/lib/omx/libOMX.Exynos.VP9.Decoder.so \
    vendor/samsung/great-common/proprietary/lib/omx/libOMX.Exynos.VP9.Encoder.so:system/lib/omx/libOMX.Exynos.VP9.Encoder.so \
    vendor/samsung/great-common/proprietary/lib/omx/libOMX.Exynos.WMV.Decoder.so:system/lib/omx/libOMX.Exynos.WMV.Decoder.so \
    vendor/samsung/great-common/proprietary/lib/soundfx/libaudioeffectoffload.so:system/lib/soundfx/libaudioeffectoffload.so \
    vendor/samsung/great-common/proprietary/lib/soundfx/libaudiopreprocessing.so:system/lib/soundfx/libaudiopreprocessing.so \
    vendor/samsung/great-common/proprietary/lib/soundfx/libaudiopreprocessing.so:system/lib/soundfx/libaudiopreprocessing.so \
    vendor/samsung/great-common/proprietary/lib/soundfx/libbundlewrapper.so:system/lib/soundfx/libbundlewrapper.so \
    vendor/samsung/great-common/proprietary/lib/soundfx/libdownmix.so:system/lib/soundfx/libdownmix.so \
    vendor/samsung/great-common/proprietary/lib/soundfx/libeffectproxy.so:system/lib/soundfx/libeffectproxy.so \
    vendor/samsung/great-common/proprietary/lib/soundfx/libgearvr.so:system/lib/soundfx/libgearvr.so \
    vendor/samsung/great-common/proprietary/lib/soundfx/libldnhncr.so:system/lib/soundfx/libldnhncr.so \
    vendor/samsung/great-common/proprietary/lib/soundfx/libmyspace.so:system/lib/soundfx/libmyspace.so \
    vendor/samsung/great-common/proprietary/lib/soundfx/libreverbwrapper.so:system/lib/soundfx/libreverbwrapper.so \
    vendor/samsung/great-common/proprietary/lib/soundfx/libvisualizer.so:system/lib/soundfx/libvisualizer.so \
    vendor/samsung/great-common/proprietary/lib64/libacryl.so:system/lib64/libacryl.so \
    vendor/samsung/great-common/proprietary/lib64/libaudiopolicyenginedefault.so:system/lib64/libaudiopolicyenginedefault.so \
    vendor/samsung/great-common/proprietary/lib64/libaudiopolicymanagerdefault.so:system/lib64/libaudiopolicymanagerdefault.so \
    vendor/samsung/great-common/proprietary/lib64/libaudiopolicymanager.so:system/lib64/libaudiopolicymanager.so \
    vendor/samsung/great-common/proprietary/lib64/libaudioutils.so:system/lib64/libaudioutils.so \
    vendor/samsung/great-common/proprietary/lib64/libbauthserver.so:system/lib64/libbauthserver.so \
    vendor/samsung/great-common/proprietary/lib64/libbauthtzcommon.so:system/lib64/libbauthtzcommon.so \
    vendor/samsung/great-common/proprietary/lib64/libcamera_client.so:system/lib64/libcamera_client.so \
    vendor/samsung/great-common/proprietary/lib64/libcamera_metadata.so:system/lib64/libcamera_metadata.so \
    vendor/samsung/great-common/proprietary/lib64/libedmnativehelper.so:system/lib64/libedmnativehelper.so \
    vendor/samsung/great-common/proprietary/lib64/libegis_fp_normal_sensor_test.so:system/lib64/libegis_fp_normal_sensor_test.so \
    vendor/samsung/great-common/proprietary/lib64/libexynoscamera3.so:system/lib64/libexynoscamera3.so \
    vendor/samsung/great-common/proprietary/lib64/libexynoscamera.so:system/lib64/libexynoscamera.so \
    vendor/samsung/great-common/proprietary/lib64/libexynosgscaler.so:system/lib64/libexynosgscaler.so \
    vendor/samsung/great-common/proprietary/lib64/libExynosOMX_Core.so:system/lib64/libExynosOMX_Core.so \
    vendor/samsung/great-common/proprietary/lib64/libExynosOMX_Resourcemanager.so:system/lib64/libExynosOMX_Resourcemanager.so \
    vendor/samsung/great-common/proprietary/lib64/libexynosscaler.so:system/lib64/libexynosscaler.so \
    vendor/samsung/great-common/proprietary/lib64/libexynosutils.so:system/lib64/libexynosutils.so \
    vendor/samsung/great-common/proprietary/lib64/libexynosv4l2.so:system/lib64/libexynosv4l2.so \
    vendor/samsung/great-common/proprietary/lib64/libfloatingfeature.so:system/lib64/libfloatingfeature.so \
    vendor/samsung/great-common/proprietary/lib64/libhiddensound.so:system/lib64/libhiddensound.so \
    vendor/samsung/great-common/proprietary/lib64/libhr.so:system/lib64/libhr.so \
    vendor/samsung/great-common/proprietary/lib64/libhwjpeg.so:system/lib64/libhwjpeg.so \
    vendor/samsung/great-common/proprietary/lib64/libion.so:system/lib64/libion.so \
    vendor/samsung/great-common/proprietary/lib64/libjackshm.so:system/lib64/libjackshm.so \
    vendor/samsung/great-common/proprietary/lib64/libjansson.so:system/lib64/libjansson.so \
    vendor/samsung/great-common/proprietary/lib64/libmediautils.so:system/lib64/libmediautils.so \
    vendor/samsung/great-common/proprietary/lib64/libprotobuf-cpp-full.so:system/lib64/libprotobuf-cpp-full.so \
    vendor/samsung/great-common/proprietary/lib64/libreference-ril.so:system/lib64/libreference-ril.so \
    vendor/samsung/great-common/proprietary/lib64/libril.so:system/lib64/libril.so \
    vendor/samsung/great-common/proprietary/lib64/librilutils.so:system/lib64/librilutils.so \
    vendor/samsung/great-common/proprietary/lib64/libsecaudioinfo.so:system/lib64/libsecaudioinfo.so \
    vendor/samsung/great-common/proprietary/lib64/libsecnativefeature.so:system/lib64/libsecnativefeature.so \
    vendor/samsung/great-common/proprietary/lib64/libsecril-client.so:system/lib64/libsecril-client.so \
    vendor/samsung/great-common/proprietary/lib64/libsec-ril-dsds.so:system/lib64/libsec-ril-dsds.so \
    vendor/samsung/great-common/proprietary/lib64/libsec-ril.so:system/lib64/libsec-ril.so \
    vendor/samsung/great-common/proprietary/lib64/libsensorhubservice.so:system/lib64/libsensorhubservice.so \
    vendor/samsung/great-common/proprietary/lib64/libsensorhub.so:system/lib64/libsensorhub.so \
    vendor/samsung/great-common/proprietary/lib64/libsensorlistener.so:system/lib64/libsensorlistener.so \
    vendor/samsung/great-common/proprietary/lib64/libsensorservice.so:system/lib64/libsensorservice.so \
    vendor/samsung/great-common/proprietary/lib64/libsetproperty.so:system/lib64/libsetproperty.so \
    vendor/samsung/great-common/proprietary/lib64/libspeexresampler.so:system/lib64/libspeexresampler.so \
    vendor/samsung/great-common/proprietary/lib64/libsynaFpSensorTestNwd.so:system/lib64/libsynaFpSensorTestNwd.so \
    vendor/samsung/great-common/proprietary/lib64/libtinyalsa.so:system/lib64/libtinyalsa.so \
    vendor/samsung/great-common/proprietary/lib64/libtlc64serviceappnative.so:system/lib64/libtlc64serviceappnative.so \
    vendor/samsung/great-common/proprietary/lib64/libtlc_direct_comm.so:system/lib64/libtlc_direct_comm.so \
    vendor/samsung/great-common/proprietary/lib64/libtlcotp.so:system/lib64/libtlcotp.so \
    vendor/samsung/great-common/proprietary/lib64/libtlc_proxy_comm.so:system/lib64/libtlc_proxy_comm.so \
    vendor/samsung/great-common/proprietary/lib64/libtlc_spay.so:system/lib64/libtlc_spay.so \
    vendor/samsung/great-common/proprietary/lib64/libtlc_tima_atn.so:system/lib64/libtlc_tima_atn.so \
    vendor/samsung/great-common/proprietary/lib64/libtlc_tima_pkm.so:system/lib64/libtlc_tima_pkm.so \
    vendor/samsung/great-common/proprietary/lib64/libtlc_tz_ccm_inapptwo.so:system/lib64/libtlc_tz_ccm_inapptwo.so \
    vendor/samsung/great-common/proprietary/lib64/libtlc_tz_dcm.so:system/lib64/libtlc_tz_dcm.so \
    vendor/samsung/great-common/proprietary/lib64/libtlc_tz_esecomm.so:system/lib64/libtlc_tz_esecomm.so \
    vendor/samsung/great-common/proprietary/lib64/libtlc_tz_iccc.so:system/lib64/libtlc_tz_iccc.so \
    vendor/samsung/great-common/proprietary/lib64/libtlc_tz_keystore.so:system/lib64/libtlc_tz_keystore.so \
    vendor/samsung/great-common/proprietary/lib64/libtzyfingr.so:system/lib64/libtzyfingr.so \
    vendor/samsung/great-common/proprietary/lib64/libuniapi.so:system/lib64/libuniapi.so \
    vendor/samsung/great-common/proprietary/lib64/libuniplugin.so:system/lib64/libuniplugin.so \
    vendor/samsung/great-common/proprietary/lib64/libwrappergps.so:system/lib64/libwrappergps.so \
    vendor/samsung/great-common/proprietary/lib64/libxml2.so:system/lib64/libxml2.so \
    vendor/samsung/great-common/proprietary/lib64/sensors.bio.so:system/lib64/sensors.bio.so \
    vendor/samsung/great-common/proprietary/lib64/sensors.sensorhub.so:system/lib64/sensors.sensorhub.so \
    vendor/samsung/great-common/proprietary/lib64/hw/audio_policy.default.so:system/lib64/hw/audio_policy.default.so \
    vendor/samsung/great-common/proprietary/lib64/hw/audio.primary.default.so:system/lib64/hw/audio.primary.default.so \
    vendor/samsung/great-common/proprietary/lib64/hw/audio.primary.goldfish.so:system/lib64/hw/audio.primary.goldfish.so \
    vendor/samsung/great-common/proprietary/lib64/hw/audio.r_submix.default.so:system/lib64/hw/audio.r_submix.default.so \
    vendor/samsung/great-common/proprietary/lib64/hw/audio.tms.default.so:system/lib64/hw/audio.tms.default.so \
    vendor/samsung/great-common/proprietary/lib64/hw/audio.usb.default.so:system/lib64/hw/audio.usb.default.so \
    vendor/samsung/great-common/proprietary/lib64/hw/camera.exynos5.so:system/lib64/hw/camera.exynos5.so \
    vendor/samsung/great-common/proprietary/lib64/hw/camera.goldfish.jpeg.so:system/lib64/hw/camera.goldfish.jpeg.so \
    vendor/samsung/great-common/proprietary/lib64/hw/camera.goldfish.so:system/lib64/hw/camera.goldfish.so \
    vendor/samsung/great-common/proprietary/lib64/hw/camera.ranchu.jpeg.so:system/lib64/hw/camera.ranchu.jpeg.so \
    vendor/samsung/great-common/proprietary/lib64/hw/camera.ranchu.so:system/lib64/hw/camera.ranchu.so \
    vendor/samsung/great-common/proprietary/lib64/hw/camera.universal8895.so:system/lib64/hw/camera.universal8895.so \
    vendor/samsung/great-common/proprietary/lib64/hw/fingerprint.default.so:system/lib64/hw/fingerprint.default.so \
    vendor/samsung/great-common/proprietary/lib64/hw/fingerprint.goldfish.so:system/lib64/hw/fingerprint.goldfish.so \
    vendor/samsung/great-common/proprietary/lib64/hw/fingerprint.ranchu.so:system/lib64/hw/fingerprint.ranchu.so \
    vendor/samsung/great-common/proprietary/lib64/hw/gatekeeper.exynos8895.so:system/lib64/hw/gatekeeper.exynos8895.so \
    vendor/samsung/great-common/proprietary/lib64/hw/gps.default.so:system/lib64/hw/gps.default.so \
    vendor/samsung/great-common/proprietary/lib64/hw/gps.goldfish.so:system/lib64/hw/gps.goldfish.so \
    vendor/samsung/great-common/proprietary/lib64/hw/gps.ranchu.so:system/lib64/hw/gps.ranchu.so \
    vendor/samsung/great-common/proprietary/lib64/hw/gralloc.default.so:system/lib64/hw/gralloc.default.so \
    vendor/samsung/great-common/proprietary/lib64/hw/gralloc.exynos5.so:system/lib64/hw/gralloc.exynos5.so \
    vendor/samsung/great-common/proprietary/lib64/hw/hwcomposer.exynos5.so:system/lib64/hw/hwcomposer.exynos5.so \
    vendor/samsung/great-common/proprietary/lib64/hw/keystore.exynos8895.so:system/lib64/hw/keystore.exynos8895.so \
    vendor/samsung/great-common/proprietary/lib64/hw/memtrack.exynos5.so:system/lib64/hw/memtrack.exynos5.so \
    vendor/samsung/great-common/proprietary/lib64/hw/nfc_nci.universal8895.so:system/lib64/hw/nfc_nci.universal8895.so \
    vendor/samsung/great-common/proprietary/lib64/hw/power.default.so:system/lib64/hw/power.default.so \
    vendor/samsung/great-common/proprietary/lib64/hw/power.exynos5.so:system/lib64/hw/power.exynos5.so \
    vendor/samsung/great-common/proprietary/lib64/hw/power.goldfish.so:system/lib64/hw/power.goldfish.so \
    vendor/samsung/great-common/proprietary/lib64/hw/sensorhubs.universal8895.so:system/lib64/hw/sensorhubs.universal8895.so \
    vendor/samsung/great-common/proprietary/lib64/hw/sensors.goldfish.so:system/lib64/hw/sensors.goldfish.so \
    vendor/samsung/great-common/proprietary/lib64/hw/sensors.ranchu.so:system/lib64/hw/sensors.ranchu.so \
    vendor/samsung/great-common/proprietary/lib64/hw/sensors.universal8895.so:system/lib64/hw/sensors.universal8895.so \
    vendor/samsung/great-common/proprietary/lib64/hw/thermal.exynos5.so:system/lib64/hw/thermal.exynos5.so \
    vendor/samsung/great-common/proprietary/lib64/hw/vibrator.default.so:system/lib64/hw/vibrator.default.so \
    vendor/samsung/great-common/proprietary/lib64/hw/vibrator.goldfish.so:system/lib64/hw/vibrator.goldfish.so \
    vendor/samsung/great-common/proprietary/lib64/hw/vr.default.so:system/lib64/hw/vr.default.so \
    vendor/samsung/great-common/proprietary/lib64/omx/libOMX.Exynos.AVC.Decoder.so:system/lib64/omx/libOMX.Exynos.AVC.Decoder.so \
    vendor/samsung/great-common/proprietary/lib64/omx/libOMX.Exynos.AVC.Encoder.so:system/lib64/omx/libOMX.Exynos.AVC.Encoder.so \
    vendor/samsung/great-common/proprietary/lib64/omx/libOMX.Exynos.HEVC.Decoder.so:system/lib64/omx/libOMX.Exynos.HEVC.Decoder.so \
    vendor/samsung/great-common/proprietary/lib64/omx/libOMX.Exynos.HEVC.Encoder.so:system/lib64/omx/libOMX.Exynos.HEVC.Encoder.so \
    vendor/samsung/great-common/proprietary/lib64/omx/libOMX.Exynos.MPEG4.Decoder.so:system/lib64/omx/libOMX.Exynos.MPEG4.Decoder.so \
    vendor/samsung/great-common/proprietary/lib64/omx/libOMX.Exynos.MPEG4.Encoder.so:system/lib64/omx/libOMX.Exynos.MPEG4.Encoder.so \
    vendor/samsung/great-common/proprietary/lib64/omx/libOMX.Exynos.VP8.Decoder.so:system/lib64/omx/libOMX.Exynos.VP8.Decoder.so \
    vendor/samsung/great-common/proprietary/lib64/omx/libOMX.Exynos.VP8.Encoder.so:system/lib64/omx/libOMX.Exynos.VP8.Encoder.so \
    vendor/samsung/great-common/proprietary/lib64/omx/libOMX.Exynos.VP9.Decoder.so:system/lib64/omx/libOMX.Exynos.VP9.Decoder.so \
    vendor/samsung/great-common/proprietary/lib64/omx/libOMX.Exynos.VP9.Encoder.so:system/lib64/omx/libOMX.Exynos.VP9.Encoder.so \
    vendor/samsung/great-common/proprietary/lib64/omx/libOMX.Exynos.WMV.Decoder.so:system/lib64/omx/libOMX.Exynos.WMV.Decoder.so \
    vendor/samsung/great-common/proprietary/vendor/etc/air_engines.xml:system/vendor/etc/air_engines.xml \
    vendor/samsung/great-common/proprietary/vendor/etc/audio_effects.conf:system/vendor/etc/audio_effects.conf \
    vendor/samsung/great-common/proprietary/vendor/etc/audio_policy.conf:system/vendor/etc/audio_policy.conf \
    vendor/samsung/great-common/proprietary/vendor/etc/public.libraries.txt:system/vendor/etc/public.libraries.txt \
    vendor/samsung/great-common/proprietary/vendor/firmware/AP_AUDIO_SLSI.bin:system/vendor/firmware/AP_AUDIO_SLSI.bin \
    vendor/samsung/great-common/proprietary/vendor/firmware/APBargeIn_AUDIO_SLSI.bin:system/vendor/firmware/APBargeIn_AUDIO_SLSI.bin \
    vendor/samsung/great-common/proprietary/vendor/firmware/APBiBF_AUDIO_SLSI.bin:system/vendor/firmware/APBiBF_AUDIO_SLSI.bin \
    vendor/samsung/great-common/proprietary/vendor/firmware/bcm4361A0_V0128.0000.hcd:system/vendor/firmware/bcm4361A0_V0128.0000.hcd \
    vendor/samsung/great-common/proprietary/vendor/firmware/bcm4361B0_V0235.0245_murata_es1.hcd:system/vendor/firmware/bcm4361B0_V0235.0245_murata_es1.hcd \
    vendor/samsung/great-common/proprietary/vendor/firmware/bcm4361B0_V0235.0245_murata.hcd:system/vendor/firmware/bcm4361B0_V0235.0245_murata.hcd \
    vendor/samsung/great-common/proprietary/vendor/firmware/bcm4361B0_V0235.0246_semco_e31.hcd:system/vendor/firmware/bcm4361B0_V0235.0246_semco_e31.hcd \
    vendor/samsung/great-common/proprietary/vendor/firmware/bcm4361B0_V0235.0247_semco.hcd:system/vendor/firmware/bcm4361B0_V0235.0247_semco.hcd \
    vendor/samsung/great-common/proprietary/vendor/firmware/bcm4361B0_V0254.0262_murata.hcd:system/vendor/firmware/bcm4361B0_V0254.0262_murata.hcd \
    vendor/samsung/great-common/proprietary/vendor/firmware/bcm4361B0_V0254.0263_semco.hcd:system/vendor/firmware/bcm4361B0_V0254.0263_semco.hcd \
    vendor/samsung/great-common/proprietary/vendor/firmware/calliope_dram.bin:system/vendor/firmware/calliope_dram.bin \
    vendor/samsung/great-common/proprietary/vendor/firmware/calliope_iva.bin:system/vendor/firmware/calliope_iva.bin \
    vendor/samsung/great-common/proprietary/vendor/firmware/calliope_sram.bin:system/vendor/firmware/calliope_sram.bin \
    vendor/samsung/great-common/proprietary/vendor/firmware/companion_2l2_master_setfile.bin:system/vendor/firmware/companion_2l2_master_setfile.bin \
    vendor/samsung/great-common/proprietary/vendor/firmware/companion_2l2_mode_setfile.bin:system/vendor/firmware/companion_2l2_mode_setfile.bin \
    vendor/samsung/great-common/proprietary/vendor/firmware/companion_fw_2l2_3h1.bin:system/vendor/firmware/companion_fw_2l2_3h1.bin \
    vendor/samsung/great-common/proprietary/vendor/firmware/companion_fw_2l2_imx320.bin:system/vendor/firmware/companion_fw_2l2_imx320.bin \
    vendor/samsung/great-common/proprietary/vendor/firmware/companion_fw_imx333_3h1.bin:system/vendor/firmware/companion_fw_imx333_3h1.bin \
    vendor/samsung/great-common/proprietary/vendor/firmware/companion_fw_imx333_imx320.bin:system/vendor/firmware/companion_fw_imx333_imx320.bin \
    vendor/samsung/great-common/proprietary/vendor/firmware/companion_imx333_master_setfile.bin:system/vendor/firmware/companion_imx333_master_setfile.bin \
    vendor/samsung/great-common/proprietary/vendor/firmware/companion_imx333_mode_setfile.bin:system/vendor/firmware/companion_imx333_mode_setfile.bin \
    vendor/samsung/great-common/proprietary/vendor/firmware/dsm.bin:system/vendor/firmware/dsm.bin \
    vendor/samsung/great-common/proprietary/vendor/firmware/dsm_tune.bin:system/vendor/firmware/dsm_tune.bin \
    vendor/samsung/great-common/proprietary/vendor/firmware/fimc_is_lib.bin:system/vendor/firmware/fimc_is_lib.bin \
    vendor/samsung/great-common/proprietary/vendor/firmware/fimc_is_rta_2l2_3h1.bin:system/vendor/firmware/fimc_is_rta_2l2_3h1.bin \
    vendor/samsung/great-common/proprietary/vendor/firmware/fimc_is_rta_2l2_imx320.bin:system/vendor/firmware/fimc_is_rta_2l2_imx320.bin \
    vendor/samsung/great-common/proprietary/vendor/firmware/fimc_is_rta_imx333_3h1.bin:system/vendor/firmware/fimc_is_rta_imx333_3h1.bin \
    vendor/samsung/great-common/proprietary/vendor/firmware/fimc_is_rta_imx333_imx320.bin:system/vendor/firmware/fimc_is_rta_imx333_imx320.bin \
    vendor/samsung/great-common/proprietary/vendor/firmware/iva10_rt-kangchen.bin:system/vendor/firmware/iva10_rt-kangchen.bin \
    vendor/samsung/great-common/proprietary/vendor/firmware/mfc_fw.bin:system/vendor/firmware/mfc_fw.bin \
    vendor/samsung/great-common/proprietary/vendor/firmware/ois_fw_dom.bin:system/vendor/firmware/ois_fw_dom.bin \
    vendor/samsung/great-common/proprietary/vendor/firmware/ois_fw_sec.bin:system/vendor/firmware/ois_fw_sec.bin \
    vendor/samsung/great-common/proprietary/vendor/firmware/score_fw_dmb0.bin:system/vendor/firmware/score_fw_dmb0.bin \
    vendor/samsung/great-common/proprietary/vendor/firmware/score_fw_dmb1.bin:system/vendor/firmware/score_fw_dmb1.bin \
    vendor/samsung/great-common/proprietary/vendor/firmware/score_fw_pmw0.bin:system/vendor/firmware/score_fw_pmw0.bin \
    vendor/samsung/great-common/proprietary/vendor/firmware/score_fw_pmw1.bin:system/vendor/firmware/score_fw_pmw1.bin \
    vendor/samsung/great-common/proprietary/vendor/firmware/setfile_2l2.bin:system/vendor/firmware/setfile_2l2.bin \
    vendor/samsung/great-common/proprietary/vendor/firmware/setfile_3h1.bin:system/vendor/firmware/setfile_3h1.bin \
    vendor/samsung/great-common/proprietary/vendor/firmware/setfile_3m3.bin:system/vendor/firmware/setfile_3m3.bin \
    vendor/samsung/great-common/proprietary/vendor/firmware/setfile_imx320.bin:system/vendor/firmware/setfile_imx320.bin \
    vendor/samsung/great-common/proprietary/vendor/firmware/setfile_imx333.bin:system/vendor/firmware/setfile_imx333.bin \
    vendor/samsung/great-common/proprietary/vendor/firmware/SoundBoosterParam.bin:system/vendor/firmware/SoundBoosterParam.bin \
    vendor/samsung/great-common/proprietary/vendor/firmware/vts.bin:system/vendor/firmware/vts.bin \
    vendor/samsung/great-common/proprietary/vendor/firmware/nfc/sec_s3nrn82_firmware.bin:system/vendor/firmware/nfc/sec_s3nrn82_firmware.bin \
    vendor/samsung/great-common/proprietary/vendor/lib/hwcomposer.exynos5.so:system/vendor/lib/hwcomposer.exynos5.so \
    vendor/samsung/great-common/proprietary/vendor/lib/libjack.so:system/vendor/lib/libjack.so \
    vendor/samsung/great-common/proprietary/vendor/lib/libMcClient.so:system/vendor/lib/libMcClient.so \
    vendor/samsung/great-common/proprietary/vendor/lib/libMcRegistry.so:system/vendor/lib/libMcRegistry.so \
    vendor/samsung/great-common/proprietary/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so \
    vendor/samsung/great-common/proprietary/vendor/lib/libOpenCv.so:system/vendor/lib/libOpenCv.so \
    vendor/samsung/great-common/proprietary/vendor/lib/libtlc_comm.so:system/vendor/lib/libtlc_comm.so \
    vendor/samsung/great-common/proprietary/vendor/lib/libtlc_tz_ccm.so:system/vendor/lib/libtlc_tz_ccm.so \
    vendor/samsung/great-common/proprietary/vendor/lib/egl/libGLES_mali.so:system/vendor/lib/egl/libGLES_mali.so \
    vendor/samsung/great-common/proprietary/vendor/lib/mediadrm/libdrmclearkeyplugin.so:system/vendor/lib/mediadrm/libdrmclearkeyplugin.so \
    vendor/samsung/great-common/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    vendor/samsung/great-common/proprietary/vendor/lib64/gralloc.exynos5.so:system/vendor/lib64/gralloc.exynos5.so \
    vendor/samsung/great-common/proprietary/vendor/lib64/hwcomposer.exynos5.so:system/vendor/lib64/hwcomposer.exynos5.so \
    vendor/samsung/great-common/proprietary/vendor/lib64/libjack.so:system/vendor/lib64/libjack.so \
    vendor/samsung/great-common/proprietary/vendor/lib64/libMcClient.so:system/vendor/lib64/libMcClient.so \
    vendor/samsung/great-common/proprietary/vendor/lib64/libMcRegistry.so:system/vendor/lib64/libMcRegistry.so \
    vendor/samsung/great-common/proprietary/vendor/lib64/libOpenCL.so:system/vendor/lib64/libOpenCL.so \
    vendor/samsung/great-common/proprietary/vendor/lib64/libOpenCv.so:system/vendor/lib64/libOpenCv.so \
    vendor/samsung/great-common/proprietary/vendor/lib64/libtlc_comm.so:system/vendor/lib64/libtlc_comm.so \
    vendor/samsung/great-common/proprietary/vendor/lib64/libtlc_tz_ccm.so:system/vendor/lib64/libtlc_tz_ccm.so \
    vendor/samsung/great-common/proprietary/vendor/lib64/egl/libGLES_mali.so:system/vendor/lib647egl/libGLES_mali.so \
    vendor/samsung/great-common/proprietary/vendor/lib64/mediadrm/libdrmclearkeyplugin.so:system/vendor/lib64/mediadrm/libdrmclearkeyplugin.so
